### PR TITLE
Restore defer for legacy alias scripts and print them in the footer

### LINKED ISSUE #67159: [Regression] Legacy script blocking change breaks Classic Cart and Checkout when a later jQuery instance replaces `window.jQuery`
#### A clear and concise description of what the bug is.

WooCommerce 11.0.0-rc.1 introduced a compatibility regression affecting Classic Shortcode-based Cart and Checkout pages on sites that load a second, non-deferred copy of jQuery after WooCommerce's frontend scripts.

In WooCommerce 10.9.4, `wc-jquery-blockui` is deferred. In WooCommerce 11.0.0-rc.1, the change introduced in [PR #64431](<https://github.com/woocommerce/woocommerce/pull/64431>) makes scripts with legacy alias handles - including `wc-jquery-blockui` - blocking.

With a later, parser-blocking jQuery include, the resulting execution sequence is:

1. WordPress jQuery loads.
2. The blocking `wc-jquery-blockui` script attaches BlockUI to that jQuery object.
3. WooCommerce's `wc-cart` and `wc-checkout` scripts remain deferred.
4. A second, non-deferred jQuery script replaces `window.jQuery`.
5. The deferred Cart and Checkout scripts execute against the replacement jQuery object, where `jQuery.blockUI`, `jQuery.fn.block`, and `jQuery.fn.unblock` do not exist.

The browser console reports:

```text
Cannot read properties of undefined (reading 'defaults')
.block is not a function
.unblock is not a function
```

This causes two customer-facing failures:

* Classic Checkout fails at `jQuery.blockUI.defaults` before `wc_checkout_form.init()` completes, so payment-method fields and details may not initialize.
* Classic Cart handlers call `preventDefault()` and then fail at `.block()` before making their Ajax request, so customers cannot update quantities or remove products.

The same setup works in WooCommerce 10.9.4 because the deferred BlockUI script executes after the later jQuery replacement and attaches itself to the final active jQuery object.

The problem has been reproduced with WooCommerce 11.0.0-rc.1 and remains reproducible with 11.0.0-rc.2.

Loading jQuery twice is a latent site-side problem. However, this report concerns the WooCommerce 11.0 loading-strategy regression that changes a previously working site into a broken Cart and Checkout. [Issue #63892](<https://github.com/woocommerce/woocommerce/issues/63892>) and PR #64431 are related but are not duplicates: they address the earlier inverse ordering problem involving legacy script handles.

#### Workarounds

* Remove the second hard-coded jQuery include and make the responsible custom code depend on WordPress's registered `jquery` handle.
* As a temporary recovery measure, remain on WooCommerce 10.9.4.

#### Write steps here

1. Set up a WordPress site with WooCommerce 10.9.4.
2. Use classic shortcode-based pages:
   1. Cart: `[woocommerce_cart]`
   2. Checkout: `[woocommerce_checkout]`
3. Create a product and add it to the cart.
4. Add the following test-only snippet. It deliberately prints a second, parser-blocking jQuery script after WordPress has printed the WooCommerce footer scripts:

```
add_action(
	'wp_footer',
	static function () {
		if ( is_cart() || is_checkout() ) {
			echo '<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>';
		}
	},
	21
);
```

 5. With WooCommerce 10.9.4 active:
    1. Open the classic Cart page.
    2. Update the product quantity and remove a product.
    3. Open the classic Checkout page and confirm that payment-method details initialize.
    4. Confirm there are no BlockUI-related errors in the browser console.
 6. Upgrade only WooCommerce to 11.0.0-rc.1 or 11.0.0-rc.2.
 7. Clear the browser console and Network log, disable browser caching, and reload the Cart page.
 8. Attempt to update a quantity or remove a product.
 9. Open the Checkout page.
10. Run this in the browser console:

```
js
({
	jqueryVersion: window.jQuery?.fn?.jquery,
	blockUI: typeof window.jQuery?.blockUI,
	block: typeof window.jQuery?.fn?.block,
	unblock: typeof window.jQuery?.fn?.unblock
})
```

#### Actual result

* The Cart controls do not complete their actions, and no corresponding Cart Ajax request is sent.
* Checkout payment-method fields or details do not initialize.
* The console reports `defaults`, `.block()`, and `.unblock()` errors.
* The console check shows the replacement jQuery version, with all three BlockUI APIs reported as `"undefined"`.

The same result can be reproduced with both WooCommerce 11.0.0-rc.1 and WooCommerce 11.0.0-rc.2.

#### A clear and concise description of what you expected to happen.

WooCommerce's declared script dependency chain should ensure that `wc-cart` and `wc-checkout` can access `jQuery.blockUI`, `jQuery.fn.block`, and `jQuery.fn.unblock` when they execute.

The loading-strategy change for legacy alias handles should not leave `wc-jquery-blockui` attached to a stale jQuery object while its dependent Cart and Checkout scripts execute against a different active jQuery object.

Classic Cart quantity/removal actions should send their requests successfully, and classic Checkout payment-method fields and details should initialize normally.

## Environment

Please fill out any of the below that applies

### PR DESCRIPTION
**Pull request by senadir**
### Changes proposed in this Pull Request:

* WooCommerce 11.0 forced scripts with legacy alias handles to be blocking ([#64431](<https://github.com/woocommerce/woocommerce/issues/64431>)), breaking classic cart/checkout on sites that load a second jQuery instance.
* Restore the defer strategy for those scripts.
* Print all frontend scripts in the footer, so blocking dependents enqueued late (e.g. payment gateway scripts) still downgrade them correctly.

Closes woocommerce/woocommerce#67159.

Bug introduced in PR [#64431](<https://github.com/woocommerce/woocommerce/issues/64431>).

### How to test the changes in this Pull Request:

1. With classic cart/checkout shortcodes, add a product to the cart.
2. Print a second jQuery copy in `wp_footer` at priority 21 (snippet in woocommerce/woocommerce#67159).
3. Cart: update quantity/remove item — no console errors, Ajax fires.
4. Checkout: payment fields initialize, no BlockUI errors.
5. Verify `wc-*` scripts print in the footer with `defer`.

<details><summary>Milestone</summary>

### Milestone

- [ ] Automatically assign milestone for the [**next WooCommerce version**](<../blob/trunk/plugins/woocommerce/woocommerce.php#L6>)

> **Note:** Check the box above to have the milestone automatically assigned when merged. Alternatively (e.g. for point releases), manually assign the appropriate milestone.

</details>

<details><summary>Changelog entry</summary>

### Changelog entry

- [ ] Automatically create a changelog entry from the details below.
- [X] This Pull Request does not require a changelog entry. (Comment required below)

+++ Changelog Entry Details

#### Significance

- [ ] Patch
- [ ] Minor
- [ ] Major

#### Type

- [ ] Fix - Fixes an existing bug
- [ ] Add - Adds functionality
- [ ] Update - Update existing functionality
- [ ] Dev - Development related task
- [ ] Tweak - A minor adjustment to the codebase
- [ ] Performance - Address performance issues
- [ ] Enhancement - Improvement to existing functionality

#### Message

+++

+++ Changelog Entry Comment

#### Comment

Created manually.

+++

</details>

<details><summary>Release Communication</summary>

### Release Communication

Select if this PR needs a generated summary for release notes:

- [ ] **Feature Highlight** - For user-facing features (what changed, user impact)
- [X] **Developer Advisory** - For developer-facing changes (what changed, how to detect, actions needed)

</details>

### CODE REVIEW

**Comment by tjcafferkey** [comment]
I get an error on shortcode cart, when updating cart after increasing quantity.

Screenshot 2026-07-31 at 13 01 22

I also get this on shortcode checkout.

Screenshot 2026-07-31 at 13 02 49

Snippet is running in the footer, priority 21. Disabling the snippet fixes both?

**Comment by senadir** [comment]
must be something in my setup, looking into it, thank you @tjcafferkey

**Comment by senadir** [comment]
also seeing the `undefinedwc` thing again in your setup, strange

**Comment by senadir** [comment]
Closing in favor of a full revert of #64431 instead.
