### ISSUE TITLE
[Regression] Legacy script blocking change breaks Classic Cart and Checkout when a later jQuery instance replaces `window.jQuery`

### ISSUE THREAD

**Issue by kamlesh08** [woocommerce/woocommerce#67159]
#### A clear and concise description of what the bug is.

WooCommerce 11.0.0-rc.1 introduced a compatibility regression affecting Classic Shortcode-based Cart and Checkout pages on sites that load a second, non-deferred copy of jQuery after WooCommerce's frontend scripts.

In WooCommerce 10.9.4, `wc-jquery-blockui` is deferred. In WooCommerce 11.0.0-rc.1, the change introduced in [PR #64431](<https://github.com/woocommerce/woocommerce/pull/64431>) makes scripts with legacy alias handles - including `wc-jquery-blockui` - blocking.

With a later, parser-blocking jQuery include, the resulting execution sequence is:

1. WordPress jQuery loads.
2. The blocking `wc-jquery-blockui` script attaches BlockUI to that jQuery object.
3. WooCommerce's `wc-cart` and `wc-checkout` scripts remain deferred.
4. A second, non-deferred jQuery script replaces `window.jQuery`.
5. The deferred Cart and Checkout scripts execute against the replacement jQuery object, where `jQuery.blockUI`, `jQuery.fn.block`, and `jQuery.fn.unblock` do not exist.

The browser console reports:

```text
Cannot read properties of undefined (reading 'defaults')
.block is not a function
.unblock is not a function
```

This causes two customer-facing failures:

* Classic Checkout fails at `jQuery.blockUI.defaults` before `wc_checkout_form.init()` completes, so payment-method fields and details may not initialize.
* Classic Cart handlers call `preventDefault()` and then fail at `.block()` before making their Ajax request, so customers cannot update quantities or remove products.

The same setup works in WooCommerce 10.9.4 because the deferred BlockUI script executes after the later jQuery replacement and attaches itself to the final active jQuery object.

The problem has been reproduced with WooCommerce 11.0.0-rc.1 and remains reproducible with 11.0.0-rc.2.

Loading jQuery twice is a latent site-side problem. However, this report concerns the WooCommerce 11.0 loading-strategy regression that changes a previously working site into a broken Cart and Checkout. [Issue #63892](<https://github.com/woocommerce/woocommerce/issues/63892>) and PR #64431 are related but are not duplicates: they address the earlier inverse ordering problem involving legacy script handles.

#### Workarounds

* Remove the second hard-coded jQuery include and make the responsible custom code depend on WordPress's registered `jquery` handle.
* As a temporary recovery measure, remain on WooCommerce 10.9.4.

#### Write steps here

1. Set up a WordPress site with WooCommerce 10.9.4.
2. Use classic shortcode-based pages:
   1. Cart: `[woocommerce_cart]`
   2. Checkout: `[woocommerce_checkout]`
3. Create a product and add it to the cart.
4. Add the following test-only snippet. It deliberately prints a second, parser-blocking jQuery script after WordPress has printed the WooCommerce footer scripts:

```
add_action(
	'wp_footer',
	static function () {
		if ( is_cart() || is_checkout() ) {
			echo '<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>';
		}
	},
	21
);
```

 5. With WooCommerce 10.9.4 active:
    1. Open the classic Cart page.
    2. Update the product quantity and remove a product.
    3. Open the classic Checkout page and confirm that payment-method details initialize.
    4. Confirm there are no BlockUI-related errors in the browser console.
 6. Upgrade only WooCommerce to 11.0.0-rc.1 or 11.0.0-rc.2.
 7. Clear the browser console and Network log, disable browser caching, and reload the Cart page.
 8. Attempt to update a quantity or remove a product.
 9. Open the Checkout page.
10. Run this in the browser console:

```
js
({
	jqueryVersion: window.jQuery?.fn?.jquery,
	blockUI: typeof window.jQuery?.blockUI,
	block: typeof window.jQuery?.fn?.block,
	unblock: typeof window.jQuery?.fn?.unblock
})
```

#### Actual result

* The Cart controls do not complete their actions, and no corresponding Cart Ajax request is sent.
* Checkout payment-method fields or details do not initialize.
* The console reports `defaults`, `.block()`, and `.unblock()` errors.
* The console check shows the replacement jQuery version, with all three BlockUI APIs reported as `"undefined"`.

The same result can be reproduced with both WooCommerce 11.0.0-rc.1 and WooCommerce 11.0.0-rc.2.

#### A clear and concise description of what you expected to happen.

WooCommerce's declared script dependency chain should ensure that `wc-cart` and `wc-checkout` can access `jQuery.blockUI`, `jQuery.fn.block`, and `jQuery.fn.unblock` when they execute.

The loading-strategy change for legacy alias handles should not leave `wc-jquery-blockui` attached to a stale jQuery object while its dependent Cart and Checkout scripts execute against a different active jQuery object.

Classic Cart quantity/removal actions should send their requests successfully, and classic Checkout payment-method fields and details should initialize normally.

## Environment

Please fill out any of the below that applies
