### PR TITLE
Fix Analytics "tz is not a function" crash from a moment.js plugin conflict

### LINKED ISSUE #64020: Analytics dashboard crash ( tz is not a function ) due to plugin conflict with moment.js
## Context

A [forum report](<https://wordpress.org/support/topic/bug-woocommerce-10-6-1-analytics-dashboard-crash-tz-is-not-a-function/>) shows Analytics dashboards crashing with `TypeError: tz is not a function` in WooCommerce 10.6.1.

Root cause: a third-party plugin clobbers the global `window.moment` after WooCommerce's bundle loads, removing the `.tz()` method added by `moment-timezone`. This was latent but surfaced by woocommerce/woocommerce#62872 (10.6.0), which expanded the conditions under which `.tz()` is called.

## Proposed fix

In `packages/js/date/src/index.ts` → `getStoreTimeZoneMoment()`, use the bundled `momentTz` import directly instead of casting the global `moment()` instance. Since `momentTz` is bundled (not externalized), it won't be affected by plugins replacing `window.moment`.

## References

* [Forum thread](<https://wordpress.org/support/topic/bug-woocommerce-10-6-1-analytics-dashboard-crash-tz-is-not-a-function/>)
* Bug introduced in PR #62872

### PR DESCRIPTION
**Pull request by chihsuan**
### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

**Context:** Analytics crashes with `TypeError: tz is not a function` when a third-party plugin replaces the global `window.moment` after WooCommerce loads, stripping the `.tz()` method that `moment-timezone` adds.

**Why the previous fix stopped working:** #64021 fixed this by relying on a bundled `moment-timezone`. Two days later #64201 externalised `moment-timezone` to `window.moment` (to fix unrelated console warnings) — undoing that protection, so `getStoreTimeZoneMoment()` again depended on the clobberable global and the crash returned.

**This change:** resolves a named time zone's current UTC offset via `date-fns-tz`'s `getTimezoneOffset()` (browser `Intl` API) and applies it with `moment().utcOffset()`, so the offset no longer depends on `window.moment`. `moment-timezone` is dropped from `@woocommerce/date`; offset/UTC-string paths are unchanged.

**Why `date-fns-tz` rather than re-bundling `moment-timezone`?** We only need the current offset for a named zone, which `Intl` (via `date-fns-tz`) provides — so this removes the dependency instead of re-introducing it. Re-bundling a private `moment-timezone` would re-add ~140 KB and can destroy `@wordpress/date`'s synthetic `WP` zone ([Gutenberg #27159](https://github.com/WordPress/gutenberg/issues/27159) — the issue #64201 was fixing), whereas the tree-shaken `getTimezoneOffset` adds only ~0.7 KB gzipped. It also nudges us toward retiring `moment`/`moment-timezone` long-term (a direction WooCommerce/WP have wanted on bundle-size grounds) by shrinking that surface rather than growing it.

Closes #64020.

(For Bug Fixes) Bug introduced in PR #64201.

### Screenshots or screen recordings:

| Before | After |
| :----- | :---- |
| Before | After |

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://developer.woocommerce.com/docs/contribution/testing/writing-high-quality-testing-instructions/), include your detailed testing instructions:

1. Set a named time zone (e.g. `America/New_York`) in **Settings → General**.
2. Go to **Analytics → Overview** and confirm it loads normally.
3. Open the DevTools console and simulate a conflicting plugin stripping moment-timezone's static method, then call the store-time-zone helper:
   ```js
   delete window.moment.tz;
   window.wc.date.getStoreTimeZoneMoment().format();
   ```
   - On `trunk`: throws `TypeError: tz is not a function`.
   - With this PR: returns the current time in the store time zone (e.g. `2026-06-24T...-04:00`) with the correct offset.
4. Confirm Analytics dates/ranges still reflect the store time zone, not the browser's.

### Testing that has already taken place:

- All 95 unit tests in `@woocommerce/date` pass; ESLint and `tsc` are clean.
- Added a regression test that removes `window.moment.tz` / `moment.prototype.tz` and asserts `getStoreTimeZoneMoment()` no longer throws and returns the correct offset.
- Verified on a local site: reproduced the crash on `trunk` (deleting `window.moment.tz` → `TypeError`), then confirmed the fixed build returns a correct DST-aware offset (`Europe/Amsterdam` → +120 in June) under the same condition.
- Bundle impact measured: the `date` chunk grows by ~0.7 KB gzipped (`date-fns-tz`'s tree-shaken `getTimezoneOffset`); no net change vs. re-bundling `moment-timezone`.

### Milestone

- [x] Automatically assign milestone for the **[next WooCommerce version](../blob/trunk/plugins/woocommerce/woocommerce.php#L6)**

> **Note:** Check the box above to have the milestone automatically assigned when merged.
> Alternatively (e.g. for point releases), manually assign the appropriate milestone.

### Changelog entry

- [ ] Automatically create a changelog entry from the details below.

- [x] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

- [ ] Patch
- [ ] Minor
- [ ] Major

#### Type

- [ ] Fix - Fixes an existing bug
- [ ] Add - Adds functionality
- [ ] Update - Update existing functionality
- [ ] Dev - Development related task
- [ ] Tweak - A minor adjustment to the codebase
- [ ] Performance - Address performance issues
- [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

Created manually in `packages/js/date/changelog/fix-64020-moment-tz-clobber`.

</details>

### Release Communication

Select if this PR needs a generated summary for release notes:

- [ ] **Feature Highlight** - For user-facing features (what changed, user impact)
- [ ] **Developer Advisory** - For developer-facing changes (what changed, how to detect, actions needed)

<details>
<summary>When to use each?</summary>

**Feature Highlight**: New features, UI changes, or improvements that merchants/store owners will notice.

- Example: "New bulk editing for products", "Improved checkout performance"

**Developer Advisory**: Breaking changes, deprecations, or changes that affect themes/plugins/extensions.

- Example: "Hook signature change", "Deprecated filter", "REST API field removed"

An AI will analyze your PR and post a draft comment for you to review and edit.

</details>

### CODE REVIEW

**Review by louwie17 — APPROVED** [review]
LGTM 🚀 Thanks for following this up @chihsuan, this tested well and changes look good 👍
