### PR TITLE
[dev] Fix blocks lint, dev and start scripts crashing on every run

### PR DESCRIPTION
**Pull request by vladolaru**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   I have assessed the impact of this change and followed the applicable [review requirements](https://github.com/woocommerce/woocommerce/blob/trunk/docs/contribution/contributing/deciding-pr-high-impact.md#review-requirements).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

The blocks `lint:js-fix`, `dev` and `start` scripts run instead of crashing. `build:check-assets` clears the same crash but still fails later, for a separate reason below.

Bug introduced in PR #56758.

**Why they crashed**

`bin/webpack-config-interactive-blocks.js` destructured `@wordpress/scripts/config/webpack.config` as an array, but that module exports an array only when `WP_EXPERIMENTAL_MODULES` is set. Without it, loading `webpack.config.js` threw `TypeError: require is not a function or its return value is not iterable`. ESLint hit it too, since the blocks flat config resolves imports through the webpack resolver.

**What changed**

- The config reads `module.rules` through an `Array.isArray` branch, so it loads whatever shape wp-scripts exports. No script needs the variable to load it any more.
- `CircularDependencyPlugin` gets a RegExp instead of an array, because it calls `exclude.test()`. It is built once, in `getSharedPlugins`, so that covers every caller. The other `exclude` options there are webpack module rules, where an array is valid.

**Why fix the config, not the scripts**

Setting the variable in the four scripts also works, and was this PR's first approach. It was never needed: the only value read is `module.rules`, which both wp-scripts configs take from the same `baseConfig` — with the flag set, the same object by identity. A production build is byte-identical either way, checked by hashing all 847 emitted files.

It also stops the pattern: since #56758, five PRs have each set this variable at one more call site, and there are nine today. Retiring those is a follow-up.

**What this does not fix**

- `build:check-assets` still exits 1 at `ajv`, which rejects `category-description` and `category-title` block.json for `"typography": true`. Those blocks have no typography controls today, so `"typography": {}` would satisfy the schema without changing the editor. Blocks team's call; I have left it.
- `start` reports 80 pre-existing cycles as errors, because `failOnError: 'warn'` is truthy where the plugin takes a boolean. It still builds and watches.
- `lint:js:report` fails on trunk for an unrelated reason: pnpm forwards its `--` to ESLint, which reads `--output-file` as a file pattern. A different bug, not touched here.

### Screenshots or screen recordings:

N/A — developer tooling only.

### How to test the changes in this Pull Request:

Prerequisites:

- Node.js 24, as set in `.nvmrc`, and pnpm 10.33.0, as pinned in the root `package.json`.
- A clone of this repository with this branch checked out, and `trunk` fetched for step 1: `git fetch origin trunk fix/blocks-lint-js-fix && git switch fix/blocks-lint-js-fix`.
- Dependencies installed from the monorepo root: `pnpm install`.
- No `WP_EXPERIMENTAL_MODULES` in your shell: `unset WP_EXPERIMENTAL_MODULES`. Every step below must pass without it.
- A terminal at the monorepo root for every command.
- Steps 3 and 4 replace your built blocks assets with a development build. Step 6 puts a production build back.

1. See the crash this fixes, by loading trunk's version of the config:

    ```sh
    CFG=plugins/woocommerce/client/blocks/bin/webpack-config-interactive-blocks.js
    git checkout origin/trunk -- "$CFG"
    (cd plugins/woocommerce/client/blocks && ./node_modules/.bin/webpack configtest webpack.config.js); echo "exit: $?"
    git checkout HEAD -- "$CFG"
    ```

    Expected: `TypeError: require is not a function or its return value is not iterable` at `bin/webpack-config-interactive-blocks.js:9:5`, then `exit: 2`.

2. Confirm the fixed config loads with the variable unset, set, and set to `false`:

    ```sh
    cd plugins/woocommerce/client/blocks
    ./node_modules/.bin/webpack configtest webpack.config.js; echo "unset: $?"
    WP_EXPERIMENTAL_MODULES=true ./node_modules/.bin/webpack configtest webpack.config.js; echo "true: $?"
    WP_EXPERIMENTAL_MODULES=false ./node_modules/.bin/webpack configtest webpack.config.js; echo "false: $?"
    cd ../../../..
    ```

    Expected: `There are no validation errors in the given webpack configuration.` three times, and `exit: 0` for all three. On trunk the first and third exit 2.

3. Run `lint:js-fix`, then undo what it fixes:

    ```sh
    pnpm --filter=@woocommerce/block-library lint:js-fix; echo "exit: $?"
    git status --short | wc -l
    git restore -- plugins/woocommerce/client/blocks
    ```

    Expected: a warning list ending in `✖ 1151 problems (0 errors, 1151 warnings)`, then `exit: 0`, then `96`, and a clean tree.

4. Run `dev`:

    ```sh
    pnpm --filter=@woocommerce/block-library dev; echo "exit: $?"
    find plugins/woocommerce/assets/client/blocks -type f | wc -l
    ```

    Expected: `webpack compiled` lines, `exit: 0`, and 1309 files.

5. Run `start`, which watches for changes:

    ```sh
    pnpm --filter=@woocommerce/block-library start
    ```

    Expected: it builds, prints `Circular dependency detected` for 80 pre-existing cycles, and keeps watching. There must be no `TypeError`. Press Ctrl+C to stop. Before the RegExp fix it died with `TypeError: plugin.options.exclude.test is not a function`.

6. Confirm `build:check-assets` still fails at its validation step, which this PR does not address, and restore a production build:

    ```sh
    pnpm --filter=@woocommerce/block-library build:check-assets; echo "exit: $?"
    pnpm --filter=@woocommerce/block-library build; echo "exit: $?"
    find plugins/woocommerce/assets/client/blocks -type f | wc -l
    ```

    Expected: `assets/js/blocks/category-description/block.json invalid`, the same for `category-title`, `should be object` for `.supports.typography`, then `exit: 1`; then the build exits 0 and leaves 1317 files.

<details>

<summary>Production output is byte-identical with the variable and without it</summary>

```sh
cd plugins/woocommerce/client/blocks
OUT=../../assets/client/blocks
hash_all () { find "$OUT" -type f | sort | xargs shasum -a 256 | shasum -a 256; }

rm -rf node_modules/.cache/webpack-* "$OUT"/*
NODE_ENV=production BABEL_ENV=default WP_EXPERIMENTAL_MODULES=true ./node_modules/.bin/webpack >/dev/null && hash_all

rm -rf node_modules/.cache/webpack-* "$OUT"/*
NODE_ENV=production BABEL_ENV=default ./node_modules/.bin/webpack >/dev/null && hash_all
```

Both print the same digest over 847 files. With the flag set, `Array.isArray` selects exactly what the old destructure selected, so this also shows the build is unchanged from trunk.

</details>

### Testing that has already taken place:

Ran on macOS with Node v24.17.0 and pnpm 10.33.0, with `WP_EXPERIMENTAL_MODULES` unset in the shell for every command.

- `webpack configtest`: exit 0 with the variable unset, set to `true`, and set to `false`. On trunk, 2 / 0 / 2.
- `lint:js-fix`: exit 0, 1151 warnings, 0 errors, 96 files fixed.
- `dev`: exit 0, 1309 files.
- `start`: 1309 files, 80 circular-dependency reports, zero `TypeError`s, still watching when stopped.
- `build:check-assets`: exit 1 at `ajv`, as on trunk. Its webpack step, run on its own past `ajv`, exits 0 and emits 613 files.
- `build`: exit 0, 1317 files including `blocks-json.php`.
- Production build with the flag versus without: 847 files each, identical file-for-file by SHA-256.
- CI paths that touch this config, all with the fix applied: `pnpm --filter=@woocommerce/block-library lint:js` exits 0 with 0 errors, and `pnpm --filter=@woocommerce/plugin-woocommerce lint:changes:branch:js` exits 0 with 0 errors. Jest never loads the webpack config.
- The changed files lint clean, with the same pre-existing `require()` warnings as before.
- Not tested on Linux or Windows.

### Milestone

- [x] Automatically assign milestone for the **[next WooCommerce version](../blob/trunk/plugins/woocommerce/woocommerce.php#L6)**

> **Note:** Check the box above to have the milestone automatically assigned when merged.
> Alternatively (e.g. for point releases), manually assign the appropriate milestone.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Comment</summary>

#### Comment

Created manually: `client/blocks/changelog/fix-blocks-webpack-config-export-shape`, a `dev` entry with a comment and no message, so nothing lands in the published changelog. `.distignore` excludes `/client/` (line 51) and `package.json` (line 40) from the release build, so none of this reaches merchants.

</details>

### Use of AI Tools

I used Claude Code (Claude Opus 5) to find the cause, run every command above, make the change, and draft this description. It also reviewed the first version of this PR, which set `WP_EXPERIMENTAL_MODULES` in the four scripts, and the measurements behind the current approach came out of that review. An AI review doesn't replace the human review this PR needs.

---

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Review by Aljullu — APPROVED** [review]
Tested a few scripts and confirming they are fixed, code changes look good to me as well.
